In [1]:
import sklearn.datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
breast_cancer= sklearn.datasets.load_breast_cancer()
feature= pd.DataFrame(breast_cancer.data, columns= breast_cancer.feature_names)
lable= breast_cancer.target

feature

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [24]:
feature.describe()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

In [25]:
feature.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [26]:
feature.shape

(569, 30)

In [27]:
from sklearn.preprocessing import MinMaxScaler
mnscaler= MinMaxScaler()



In [28]:
feature= mnscaler.fit_transform(feature)

In [29]:
feature

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [30]:
lr=1
w= np.ones(feature.shape[1])

b=0

accuracy= {}
max_accuracy= 0
wt_matrix= []

wt_matrix.append(w)
epoches= 100
sim= []

In [31]:
w

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
w.shape

(30,)

In [35]:
for j in range(1,epoches):
  for i in range(feature.shape[0]):
    yin= np.dot(w,feature[i])

    if yin>=b:
      y_pred=1

    else:
      y_pred=0

    if lable[i]== 1 and y_pred== 0:
      w= w+lr * feature[i]

    elif lable[i] == 0 and y_pred ==1:
      w= w-lr * feature[i]
  wt_matrix.append(w)
  cos_sim= cosine_similarity(wt_matrix[j-1].reshape(1,-1),wt_matrix[j].reshape(1,-1))
  sim.append(cos_sim)

h_matching= sim.index(max(sim))
final_weight= wt_matrix[h_matching] 
  


In [36]:
final_weight

array([ 17.05083061,  -2.20865742,  13.4193214 ,  -7.96805938,
         3.19220005,  -3.82559352, -14.18150187, -12.48957753,
         7.58585859,  13.02169334,  -7.4270143 ,   2.79466496,
        -1.94468266, -13.48851509,  -5.07930788,   0.73299636,
         6.88659343,   0.77224853,   7.03208195,   8.54677459,
        -2.00305941,  -2.00506397,  -0.67851985, -19.71401888,
         3.06035792,  -0.95033521,   2.58816853,   1.31762543,
        -9.58170708,  -5.92535747])